include ../conf.inc

all:	     live1 live2 live3 live4 live5 live6 live7 live8

live1:  
	     $(GPP) live1.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live1.x

live2:  
	     $(GPP) live2.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live2.x

live3:  
	     $(GPP) live3.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live3.x

live4:  
	     $(GPP) live4.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live4.x
	     
live5:  
	     $(GPP) live5.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live5.x

live6:  
	     $(GPP) live6.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live6.x

live7:  
	     $(GPP) live7.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live7.x

live8:  
	     $(GPP) live8.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live8.x
   	     
clean:
	     rm *.x
