include ../conf.inc

all:	     live1 live2 live3 live4 live5

live1:  
	     $(GPP) live1.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live1.x

live2:  
	     $(GPP) live2.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live2.x

live3:  
	     $(GPP) live3.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live3.x

live4:  
	     $(GPP) live4.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live4.x

live5:  
	     $(GPP) live5.cpp $(CFLAGS) $(LDFLAGS) $(FLAGS) -o live5.x

clean:
	     rm *.x
